server:
  port: 8120
  address: localhost
spring:
  datasource:
    driver-class-name: dm.jdbc.driver.DmDriver
    url: jdbc:dm://localhost:5236/
    username: SYSDBA
    password: SYSDBA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect
    hibernate:
      ddl-auto: none
    show-sql: true
#    下面这个版本的配置会报错，报那个 Failed to determine a suitable driver class
#server:
#  port: 8086
#spring:
#  #数据源配置
#  datasource:
#    url: jdbc:dm://localhost:5236/DMSERVER?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: SYSDBA
#    password: SYSDBA
#  jpa:
#    ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.DmDialect
#  jpa:
#    #这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    #配置在日志中打印出执行的 SQL 语句信息。
#    show-sql: true
#    hibernate:
#      #配置指明在程序启动的时候要删除并且创建实体类对应的表
#      ddl-auto: create
#数据访问层标准配置
#hibernate:
#  dialect: org.hibernate.dialect.DmDialect
#  show_sql: false
#  format_sql: true
#  use_sql_comments: true
#  max_fetch_depth: 1
#  generate_statistics: false
#  current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
#  jdbc:
#    batch_size: 300
#  cache:
#    use_second_level_cache: false
#    provider_class: net.sf.ehcache.hibernate.EhCacheProvider
#    region:
#      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
#  hbm2ddl:
#    auto: none
